# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

# on:
#   push:
#     branches:
#       - "main"

on:
  repository_dispatch:
    types: [release_docker_image]

jobs:
  docker_publish_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        working-directory: ./packages/lpms-server
        env:
          LPMS_SERVER_TAG: ${{secrets.LPMS_SERVER_TAG}}
        run: ./build.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        working-directory: ./packages/lpms-server
        run: docker push windingtree/lpms-server:${{secrets.LPMS_SERVER_TAG}}
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a appname web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a appname web

      # - name: Heroku login
      #   env:
      #     # HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      #     HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      #   working-directory: ./packages/lpms-server
      #   run: |
      #     heroku container:login
      # - name: Heroku pull docker image
      #   env:
      #     # HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      #     HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      #   working-directory: ./packages/lpms-server
      #   run: |
      #     docker tag windingtree/lpms-server:test registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
      #     docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
